- name: install fish shell
  apt:
    name: fish
    state: present

- name: Add shell integration to fish configuration
  block:
    - name: Ensure fish config directory exists
      file:
        path: ~/.config/fish
        state: directory
