- name: Workplace setup
  hosts: localhost
  become: true

  tasks:
    - name: update apt
      apt:
        update_cache: yes

  roles:
    # common
    - { role: git }
    - { role: fish }
    # terminal
    - { role: fzf }
    - { role: zoxide }
    - { role: oh-my-posh }
    - { role: lazygit }
    # desktop applications
    - { role: brave }
    - { role: chrome }
    # development
    - { role: neovim }
    - { role: zed }
    # - { role: vs-code }
    # - { role: warp }
