- name: Add Visual Studio Code repository key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Visual Studio Code repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
